extends RefCounted

func run(t) -> void:
	var text := FileAccess.get_file_as_string("res://scripts/sound_manager.gd")
	t.is_true(text.contains("const ENABLE_MUSIC := true"), "全局音乐应默认启用")
	t.is_true(text.contains("const ENABLE_ANDROID_LOOPING_BGM := false"), "Android 应默认关闭 WAV 原生循环，改用安全重启")
	t.is_true(text.contains("GUNSHOT_NEAR_DISTANCE") and text.contains("GUNSHOT_FAR_DISTANCE"), "枪声应有近远距离衰减参数")
	t.is_true(text.contains("func play_shot(weapon_id: String, source_position: Vector3 = Vector3.ZERO, spatialized: bool = false)"), "枪声播放应支持空间位置和距离音量")
	t.is_true(text.contains("func _gunshot_volume_db") and text.contains("source_position.distance_to(listener)"), "枪声应根据听者距离计算音量")
	t.is_true(text.contains("func _get_listener_position()") and text.contains("get_camera_3d()"), "枪声距离应优先以当前相机作为听者位置")
	t.is_true(text.contains("exp(-t * 58.0)") and text.contains("exp(-t * 34.0)"), "枪声波形应使用爆裂/尾音包络提升真实感")
	t.is_true(text.contains("func play_menu_music()"), "应提供菜单音乐入口")
	t.is_true(text.contains("func play_combat_music()"), "应提供战斗音乐入口")
	t.is_true(text.contains("func _on_music_finished()"), "Android 非原生循环音乐应能播放完后重启")
	t.is_true(text.contains("var _stream_cache: Dictionary = {}"), "固定音效应缓存复用，避免频繁创建/释放音频流")
	t.is_true(text.contains("func _get_cached_stream(key: String)"), "应存在统一音效缓存入口")
	t.is_true(text.contains("if player.playing:"), "复用音效播放器前应检查播放状态")
	t.is_true(text.contains("player.stop()"), "复用音效播放器前应停止旧流，避免替换播放中的 AudioStream")
	t.is_true(text.contains("OS.has_feature(\"android\") and not ENABLE_ANDROID_LOOPING_BGM"), "Android 音乐循环策略应在配置函数中生效")
	t.is_true(text.contains("const ENABLE_FOOTSTEP_SFX := false"), "脚步音默认应关闭，避免移动时叠加蜂鸣")
	t.is_true(text.contains("EMPTY_CLICK_MIN_INTERVAL_MSEC"), "空仓音效应限频，避免长按没子弹时蜂鸣")
	t.is_true(text.contains("if now - _last_empty_click_msec < EMPTY_CLICK_MIN_INTERVAL_MSEC"), "空仓音效限频逻辑应生效")
	t.is_true(text.contains("去掉高频纯音避免蜂鸣"), "空仓音效应移除高频纯音")
	t.is_true(text.contains("去掉叮叮纯音"), "拾取音效应移除蜂鸣式纯音")
	t.is_true(text.contains("wav.loop_mode = AudioStreamWAV.LOOP_DISABLED"), "短音效默认不应循环")
	t.is_true(text.contains("music.loop_end = int(music.data.size() / 2.0)"), "音乐 loop_end 应使用浮点除法后显式转整型，避免整数除法警告")
	t.is_true(text.contains("func _make_menu_music()") and text.contains("func _make_combat_music()"), "应生成原创菜单音乐和原创战斗音乐")
	t.is_false(text.contains("music.data.size() / 2  ##"), "音乐 loop_end 不应使用会触发警告的整数除法")

	var main_menu_text := FileAccess.get_file_as_string("res://scripts/main_menu.gd")
	var map_select_text := FileAccess.get_file_as_string("res://scripts/map_select.gd")
	var settings_text := FileAccess.get_file_as_string("res://scripts/settings_menu.gd")
	var match_text := FileAccess.get_file_as_string("res://scripts/match_manager.gd")
	t.is_true(main_menu_text.contains("SoundManager.play_menu_music()"), "首页应播放菜单音乐")
	t.is_true(map_select_text.contains("SoundManager.play_menu_music()"), "地图选择页应播放菜单音乐")
	t.is_true(settings_text.contains("SoundManager.play_menu_music()"), "设置页应播放菜单音乐")
	t.is_true(match_text.contains("SoundManager.play_combat_music()"), "战斗开始应播放战斗音乐")
