extends RefCounted

const MAIN_MENU_PATH := "res://scripts/main_menu.gd"

func run(t) -> void:
	var source := FileAccess.get_file_as_string(MAIN_MENU_PATH)
	t.is_true(source.contains("const TUTORIAL_STEPS"), "Main menu should keep step-by-step tutorial content")
	t.is_true(source.contains("if not PlayerData.tutorial_completed"), "First launch should check tutorial completion")
	t.is_true(source.contains("call_deferred(\"_show_tutorial\", true)"), "Unfinished tutorial should auto-open")
	t.is_true(source.contains("_set_tutorial_step"), "Tutorial should support step switching")
	t.is_true(source.contains("上一步"), "Tutorial should support going back")
	t.is_true(source.contains("下一步"), "Tutorial should support going forward")
	t.is_true(source.contains("开始作战"), "Final step should lead into battle")
	t.is_true(source.contains("PlayerData.mark_tutorial_completed(true)"), "Tutorial completion should be saved")
	t.is_true(source.contains("func _build_side_actions(star_label: Label)"), "Mobile home should tuck daily actions into the side")
	t.is_true(source.contains("SideDailyActions"), "Home should have a side daily action container")
	t.is_true(source.contains("func _make_edge_button(text: String)"), "Home should provide side button styling")
	t.is_true(source.contains("func _show_daily_hub(star_label: Label)"), "Daily entry should open a daily hub")
	t.is_true(source.contains("DailyHubOverlay"), "Daily rewards and tasks should be shown in an overlay")
	t.is_true(source.contains("每日奖励 / 每日任务已收纳到右侧按钮"), "Home should explain daily content is tucked away")
	t.is_false(source.contains("root.add_child(daily_button)"), "Daily reward should not occupy the main first screen")
	t.is_false(source.contains("root.add_child(_build_daily_tasks_panel(star_label))"), "Daily task panel should not be directly on the first screen")
	t.is_true(source.contains("func _is_mobile_layout()"), "Home layout should adapt to mobile screens")
	t.is_true(source.contains("get_viewport_rect().size"), "Mobile detection should use viewport size")
	t.is_true(source.contains("var viewport_size := get_viewport_rect().size"), "Mobile detection variable should not shadow Control.size")
	t.is_false(source.contains("var size := get_viewport_rect().size"), "Home should not shadow Control.size")
	t.is_true(source.contains("panel.custom_minimum_size = Vector2(320 if _is_mobile_layout() else 560, 0)"), "Daily overlay should be compact on mobile")
	t.is_true(source.contains("1. 任务目标"), "Tutorial should explain mission goals")
	t.is_true(source.contains("2. 移动与瞄准"), "Tutorial should explain movement and aiming")
	t.is_true(source.contains("3. 射击、装弹与切枪"), "Tutorial should explain shooting, reload, and switching")
	t.is_true(source.contains("4. 武器定位"), "Tutorial should explain weapon roles")
	t.is_true(source.contains("5. 星星与地图"), "Tutorial should explain stars and maps")
	t.is_true(source.contains("战术匕首"), "Tutorial should mention the tactical knife loadout")
