extends RefCounted

const MAIN_MENU_PATH := "res://scripts/main_menu.gd"

func run(t) -> void:
	var source := FileAccess.get_file_as_string(MAIN_MENU_PATH)
	t.is_true(source.contains("const TUTORIAL_STEPS"), "首页应维护分步骤教程内容")
	t.is_true(source.contains("if not PlayerData.tutorial_completed"), "首次进入首页应检查教程完成状态")
	t.is_true(source.contains("call_deferred(\"_show_tutorial\", true)"), "未完成教程时应自动弹出首局引导")
	t.is_true(source.contains("_set_tutorial_step"), "教程应支持步骤切换")
	t.is_true(source.contains("上一步"), "教程应支持返回上一步")
	t.is_true(source.contains("下一步"), "教程应支持进入下一步")
	t.is_true(source.contains("开始作战"), "最后一步应引导玩家开始作战")
	t.is_true(source.contains("PlayerData.mark_tutorial_completed(true)"), "完成或跳过教程后应保存完成状态")
	t.is_true(source.contains("func _build_side_actions(star_label: Label)"), "手机首页应把每日奖励/任务收纳到边缘小按钮")
	t.is_true(source.contains("SideDailyActions"), "首页应存在侧边每日入口容器")
	t.is_true(source.contains("func _make_edge_button(text: String)"), "首页应提供侧边每日按钮样式")
	t.is_true(source.contains("func _show_daily_hub(star_label: Label)"), "点击每日入口应打开每日补给弹层")
	t.is_true(source.contains("DailyHubOverlay"), "每日奖励和任务应在弹层中展示")
	t.is_true(source.contains("每日奖励 / 每日任务已收纳到右侧按钮"), "首屏应提示每日内容已收纳，降低拥挤感")
	t.is_false(source.contains("root.add_child(daily_button)"), "每日奖励不应再作为首页主按钮直接占用首屏")
	t.is_false(source.contains("root.add_child(_build_daily_tasks_panel(star_label))"), "每日任务面板不应再直接显示在首页首屏")
	t.is_true(source.contains("func _is_mobile_layout()"), "首页布局应根据手机屏幕做紧凑适配")
	t.is_true(source.contains("get_viewport_rect().size"), "移动端判断应参考当前视口尺寸")
	t.is_true(source.contains("panel.custom_minimum_size = Vector2(320 if _is_mobile_layout() else 560, 0)"), "每日任务弹层应在手机上使用紧凑宽度")
	t.is_true(source.contains("1. 任务目标"), "教程应说明任务目标")
	t.is_true(source.contains("2. 移动与瞄准"), "教程应说明移动与瞄准")
	t.is_true(source.contains("3. 射击、装弹与切枪"), "教程应说明射击、装弹与切枪")
	t.is_true(source.contains("4. 武器定位"), "教程应说明武器定位")
	t.is_true(source.contains("5. 星星与地图"), "教程应说明星星与地图")
