extends RefCounted

func run(t) -> void:
	t.resource_exists("res://scenes/mobile_controls.tscn", "移动端触控场景必须存在")
	var mobile_text := FileAccess.get_file_as_string("res://scripts/mobile_controls.gd")
	var hud_text := FileAccess.get_file_as_string("res://scripts/hud.gd")
	var player_text := FileAccess.get_file_as_string("res://scripts/player_controller.gd")

	t.is_true(mobile_text.contains("func _is_gameplay_input_enabled()"), "移动端输入应有统一可用状态判断")
	t.is_true(mobile_text.contains("func _is_gameplay_touch_enabled()"), "触摸视角应有真实触屏状态判断")
	t.is_true(mobile_text.contains("_look_area.mouse_filter = Control.MOUSE_FILTER_STOP if should_block else Control.MOUSE_FILTER_IGNORE"), "视角触摸区应按战斗状态启停拦截")
	t.is_true(mobile_text.contains("if not should_block:"), "视角触摸区停用时应清理摇杆/开火状态")
	t.is_true(mobile_text.contains("player.set_mobile_look(event.relative)"), "右半屏拖动应继续驱动视角旋转")
	t.is_true(mobile_text.contains("event is InputEventScreenDrag and event.index != joystick_touch_id"), "摇杆触点不应同时驱动视角旋转")
	t.is_true(mobile_text.contains("fire_touch_id"), "开火应有独立触点，支持移动和开火多指并发")
	t.is_true(mobile_text.contains("elif event is InputEventScreenDrag and event.index == fire_touch_id"), "按住开火触点拖动时应继续驱动视角旋转")
	t.is_true(mobile_text.contains("func _fire_rect(viewport_size: Vector2)"), "开火按钮应支持手动触点命中检测")
	t.is_true(mobile_text.contains("func _right_fire_rect(viewport_size: Vector2)"), "右侧开火按钮应有独立命中区域")
	t.is_true(mobile_text.contains("func _left_fire_rect(viewport_size: Vector2)"), "左侧居中开火按钮应有独立命中区域")
	t.is_true(mobile_text.contains("func _is_fire_position(position: Vector2, viewport_size: Vector2)"), "左右开火区域应统一命中判断")
	t.is_true(mobile_text.contains("RIGHT_FIRE_SHIFT_LEFT := FIRE_BUTTON_DIAMETER / 3.0"), "右下角开火按钮应左移约 1/3 直径")
	t.is_true(mobile_text.contains("left_fire_btn"), "屏幕最左侧垂直居中应增加开火键")
	t.is_true(mobile_text.contains("func _reload_rect(viewport_size: Vector2)"), "装弹按钮应支持手动触点命中检测")
	t.is_true(mobile_text.contains("func _weapon_rect(viewport_size: Vector2)"), "切枪按钮应支持手动触点命中检测")
	t.is_true(mobile_text.contains("func _jump_rect(viewport_size: Vector2)"), "跳跃按钮应支持手动触点命中检测")
	t.is_true(mobile_text.contains("jump_btn"), "右下角开火键左边应增加跳跃按钮")
	t.is_true(mobile_text.contains("player.mobile_jump()"), "跳跃按钮应调用玩家移动端跳跃")
	t.is_true(player_text.contains("const MOBILE_JUMP_HEIGHT := 0.9"), "移动端跳跃高度应约为半个人高度")
	t.is_true(player_text.contains("func mobile_jump()"), "玩家应暴露移动端跳跃方法")
	t.is_true(mobile_text.contains("func _reset_all_inputs()"), "战斗输入停用时应统一清理所有移动端状态")
	t.is_true(mobile_text.contains("fire_btn.button_down.connect"), "开火按钮应响应按下事件")
	t.is_true(mobile_text.contains("fire_btn.button_up.connect"), "开火按钮应响应松开事件")
	t.is_true(mobile_text.contains("player.mobile_reload()"), "装弹按钮应调用玩家装弹")
	t.is_true(mobile_text.contains("player.mobile_next_weapon()"), "切枪按钮应调用玩家切枪")
	t.is_true(mobile_text.contains("func _request_next_weapon()"), "切枪按钮应通过统一入口去抖，避免一次点击多次切枪")
	t.is_true(mobile_text.contains("WEAPON_BUTTON_DEBOUNCE_MSEC"), "移动端切枪按钮应有短时间去抖保护")
	t.is_true(player_text.contains("func _play_weapon_switch_animation"), "玩家第一人称武器切换应有动态动作")
	t.is_true(player_text.contains("TRANS_BACK"), "切枪动画应带回弹感")

	t.is_true(player_text.contains("func can_accept_mobile_input()"), "玩家应暴露移动端输入可用状态")
	t.is_true(player_text.contains("not _dead") and player_text.contains("match_manager.match_over"), "死亡或结算后应拒绝移动端战斗输入")

	t.is_true(hud_text.contains("root.mouse_filter = Control.MOUSE_FILTER_IGNORE"), "HUD 全屏根节点不应吞掉移动端触摸")
	t.is_true(hud_text.contains("top.mouse_filter = Control.MOUSE_FILTER_IGNORE"), "HUD 顶部信息条不应吞掉移动端触摸")
	t.is_true(hud_text.contains("bottom.mouse_filter = Control.MOUSE_FILTER_IGNORE"), "HUD 底部信息条不应吞掉移动端触摸")
	t.is_true(hud_text.contains("func _should_show_control_hint()"), "HUD 应集中判断是否显示桌面操作提示")
	t.is_true(hud_text.contains("if _should_show_control_hint():"), "Android/iOS 战斗页不应创建底部 WASD 操作提示块")
	t.is_true(hud_text.contains("if hint_label != null:"), "移动端隐藏提示块后结算更新应判空")
	t.is_true(hud_text.contains("label.mouse_filter = Control.MOUSE_FILTER_IGNORE"), "HUD 文本标签不应吞掉移动端触摸")
	t.is_true(hud_text.contains("rect.mouse_filter = Control.MOUSE_FILTER_IGNORE"), "准星节点不应吞掉移动端触摸")
	t.is_true(hud_text.contains("result_panel.mouse_filter = Control.MOUSE_FILTER_STOP"), "结算面板应保留按钮点击拦截")
	t.is_true(hud_text.contains("func _queue_free_if_valid(node: Node)"), "HUD 延迟清理节点前应检查有效性，避免 queue_free 空引用")
	t.is_true(hud_text.contains("timeout.connect(_queue_free_if_valid.bind(p))"), "纸屑延迟清理应绑定当前粒子并安全释放")
