extends RefCounted

func run(t) -> void:
	t.resource_exists("res://scenes/mobile_controls.tscn", "Mobile controls scene should exist")
	var mobile_text := FileAccess.get_file_as_string("res://scripts/mobile_controls.gd")
	var hud_text := FileAccess.get_file_as_string("res://scripts/hud.gd")
	var player_text := FileAccess.get_file_as_string("res://scripts/player_controller.gd")

	t.is_true(mobile_text.contains("func _is_gameplay_input_enabled()"), "Mobile input should have a shared enabled-state check")
	t.is_true(mobile_text.contains("func _is_gameplay_touch_enabled()"), "Touch look should check real touch-control state")
	t.is_true(mobile_text.contains("_look_area.mouse_filter = Control.MOUSE_FILTER_STOP if should_block else Control.MOUSE_FILTER_IGNORE"), "Look area should block only during active mobile gameplay")
	t.is_true(mobile_text.contains("if not should_block:"), "Controls should reset when touch input is disabled")
	t.is_true(mobile_text.contains("player.set_mobile_look(event.relative)"), "Touch drag should rotate the view")
	t.is_true(mobile_text.contains("event.index != joystick_touch_id"), "Joystick touch should not also rotate the view")
	t.is_true(mobile_text.contains("fire_touch_id"), "Right fire should have its own touch id")
	t.is_true(mobile_text.contains("left_fire_touch_id"), "Left fire should have its own touch id")
	t.is_true(mobile_text.contains("elif event is InputEventScreenDrag and event.index == fire_touch_id"), "Dragging the right fire button should keep aiming")
	t.is_true(mobile_text.contains("JOYSTICK_START_X_OFFSET := 34.0"), "Joystick should be nudged right")
	t.is_true(mobile_text.contains("JOYSTICK_START_Y_OFFSET := -34.0"), "Joystick should be nudged upward")
	t.is_true(mobile_text.contains("RIGHT_FIRE_MARGIN_X := 44.0"), "Right fire button should be anchored near the lower-right corner")
	t.is_true(mobile_text.contains("FIRE_BUTTON_DIAMETER := 184.0"), "Right fire button should be larger")
	t.is_true(mobile_text.contains("LEFT_FIRE_BUTTON_DIAMETER := 132.0"), "Left upper fire button should be present")
	t.is_true(mobile_text.contains("WEAPON_BUTTON_DIAMETER := 104.0"), "Weapon switch button should sit between fire and jump")
	t.is_true(mobile_text.contains("func _right_fire_rect(viewport_size: Vector2)"), "Right fire hit area should be explicit")
	t.is_true(mobile_text.contains("func _left_fire_rect"), "Left fire hit area should be explicit")
	t.is_true(mobile_text.contains("func _weapon_rect(viewport_size: Vector2)"), "Weapon switch hit area should be explicit")
	t.is_true(mobile_text.contains("func _jump_rect(viewport_size: Vector2)"), "Jump hit area should be explicit")
	t.is_true(mobile_text.contains("player.mobile_jump()"), "Jump button should call mobile_jump")
	t.is_true(player_text.contains("const JUMP_HEIGHT := 5.4"), "Jump height should be about three people")
	t.is_true(player_text.contains("const SECOND_JUMP_HEIGHT := 2.7"), "Second jump height should be about one and a half people")
	t.is_true(player_text.contains("const MOBILE_JUMP_HEIGHT := JUMP_HEIGHT"), "Mobile jump height should match desktop")
	t.is_true(player_text.contains("_air_jumps_used < 1"), "Player should support one extra air jump")
	t.is_true(player_text.contains("var _jump_started := false"), "Jump state should remember that the first jump has started")
	t.is_true(player_text.contains("func _try_jump()"), "Jump and mobile jump should share the same double-jump logic")
	t.is_true(player_text.contains("_jump_started and _air_jumps_used < 1"), "Second jump should trigger after the first jump has started")
	t.is_true(player_text.contains("_play_jump_motion(true)"), "Second jump should play a stronger first-person jump animation")
	t.is_true(player_text.contains("if input_dir.length() > 0.01:"), "Air movement should continue to accept input")
	t.is_true(player_text.contains("SCOPE_ZOOM_LEVELS := [1.0, 2.5, 5.0]"), "Guns should support 2.5x and 5.0x aim zoom")
	t.is_true(player_text.contains("_scope_index = (_scope_index + 1) % SCOPE_ZOOM_LEVELS.size()"), "Scope button should cycle 2.5x, 5.0x, then close")
	t.is_true(player_text.contains("signal player_scope_changed(active: bool, weapon_id: String)"), "Player should notify HUD when scope state changes")
	t.is_true(hud_text.contains("_scope_overlay"), "HUD should include a scope overlay")
	t.is_true(hud_text.contains("weapon_id == \"barrett\""), "Barrett should use scope overlay when aiming")
	t.is_true(player_text.contains("func mobile_toggle_scope()"), "Player should expose mobile scope toggling")
	t.is_true(player_text.contains("weapon_system.get_current_weapon_id() == \"knife\""), "Knife should reset scope zoom instead of aiming")
	t.is_true(mobile_text.contains("func _reset_all_inputs()"), "Mobile controls should reset all touch state together")
	t.is_true(mobile_text.contains("_action_button_layer.visible = should_show_actions"), "Action buttons should hide during spectate/results")
	t.is_true(mobile_text.contains("_is_gameplay_input_enabled() and player != null"), "Button callbacks should guard gameplay state")
	t.is_true(mobile_text.contains("fire_btn.button_down.connect"), "Right fire should respond to press")
	t.is_true(mobile_text.contains("fire_btn.button_up.connect"), "Right fire should respond to release")
	t.is_true(mobile_text.contains("left_fire_btn.button_down.connect"), "Left fire should respond to press")
	t.is_true(mobile_text.contains("player.mobile_reload()"), "Reload button should call mobile_reload")
	t.is_true(mobile_text.contains("player.mobile_next_weapon()"), "Weapon button should call mobile_next_weapon")
	t.is_true(mobile_text.contains("SCOPE_BUTTON_DIAMETER := 88.0"), "Mobile controls should include a scope button")
	t.is_true(mobile_text.contains("player.mobile_toggle_scope()"), "Scope button should call mobile_toggle_scope")
	t.is_true(mobile_text.contains("SCOPE_BUTTON_DEBOUNCE_MSEC"), "Scope button should debounce taps to avoid skipping zoom levels")
	t.is_true(mobile_text.contains("func _request_scope_toggle()"), "Scope touch area and button should share one debounced toggle")
	t.is_true(mobile_text.contains("func _scope_rect(viewport_size: Vector2)"), "Scope hit area should be explicit")
	t.is_true(mobile_text.contains("GRENADE_BUTTON_DIAMETER := 92.0"), "Mobile controls should include a grenade button")
	t.is_true(mobile_text.contains("player.mobile_throw_grenade()"), "Grenade button should throw a grenade")
	t.is_true(mobile_text.contains("func _grenade_rect(viewport_size: Vector2)"), "Grenade hit area should be explicit")
	t.is_true(player_text.contains("func mobile_throw_grenade()"), "Player should expose mobile grenade throwing")
	t.is_true(player_text.contains("GRENADE_PROJECTILE_SCENE"), "Grenade should use the projectile scene")
	t.is_true(player_text.contains("GRENADE_COOLDOWN := 2.0"), "Grenade should be ready every two seconds")
	t.is_true(player_text.contains("GRENADE_MAX_PER_ROUND := 10"), "Player should have at most ten grenades each round")
	t.is_true(player_text.contains("func get_auto_rpg_remaining()"), "Player should expose auto RPG countdown")
	t.is_true(player_text.contains("func get_grenades_remaining()"), "Player should expose remaining grenade count")
	t.is_true(player_text.contains("_grenades_remaining -= 1"), "Throwing a grenade should consume one grenade")
	t.is_true(player_text.contains("_grenade_timer > 0.0"), "Grenade should only throw after cooldown is ready")
	t.is_true(player_text.contains("_grenades_remaining <= 0"), "Grenade throwing should stop when all grenades are used")
	t.is_true(player_text.contains("setup_arc"), "Grenade should be thrown in an arc")
	t.is_true(hud_text.contains("auto_rpg_label"), "HUD should show auto RPG countdown")
	t.is_true(hud_text.contains("grenades_remaining"), "Grenade remaining count should be shown at the top")
	t.is_true(player_text.contains("PRONE_BODY_HEIGHT := STANDING_BODY_HEIGHT / 5.0"), "Prone height should be one fifth of standing height")
	t.is_true(player_text.contains("func is_prone() -> bool"), "Player should expose prone state for AI detection")
	t.is_true(player_text.contains("func mobile_toggle_prone()"), "Player should expose mobile prone toggling")
	t.is_true(mobile_text.contains("PRONE_BUTTON_DIAMETER := 88.0"), "Mobile controls should include a prone button")
	t.is_true(mobile_text.contains("player.mobile_toggle_prone()"), "Prone button should toggle prone")
	t.is_false(mobile_text.contains("icon_label.text = \"F\""), "Fire icon should not be a letter")
	t.is_false(mobile_text.contains("icon_label.text = \"R\""), "Reload icon should not be a letter")
	t.is_false(mobile_text.contains("icon_label.text = \"W\""), "Weapon icon should not be a letter")
	t.is_false(mobile_text.contains("icon_label.text = \"Z\""), "Scope icon should not be a letter")
	t.is_true(mobile_text.contains("WEAPON_BUTTON_DEBOUNCE_MSEC"), "Weapon button should debounce taps")
	t.is_true(player_text.contains("func _play_weapon_switch_animation"), "First-person weapon switching should be animated")
	t.is_true(player_text.contains("TRANS_BACK"), "Weapon switch animation should have a snap-back feel")
	t.is_true(player_text.contains("func _play_jump_motion(second_jump: bool)"), "Jumping should have high quality first-person motion feedback")
	t.is_true(player_text.contains("func _reset_first_person_state_for_spectate()"), "Spectator mode should clear player aim/prone/jump camera state")
	t.is_true(player_text.contains("camera.fov = BASE_CAMERA_FOV"), "Spectator mode should reset zoomed camera FOV")
	t.is_true(player_text.contains("func can_accept_mobile_input()"), "Player should expose mobile input state")
	t.is_true(player_text.contains("not _dead") and player_text.contains("match_manager.match_over"), "Dead or finished matches should reject mobile combat input")

	t.is_true(hud_text.contains("root.mouse_filter = Control.MOUSE_FILTER_IGNORE"), "HUD root should not swallow mobile touches")
	t.is_true(hud_text.contains("top.mouse_filter = Control.MOUSE_FILTER_IGNORE"), "HUD top bar should not swallow mobile touches")
	t.is_true(hud_text.contains("bottom.mouse_filter = Control.MOUSE_FILTER_IGNORE"), "HUD bottom bar should not swallow mobile touches")
	t.is_true(hud_text.contains("func _should_show_control_hint()"), "HUD should centralize desktop control hint visibility")
	t.is_true(hud_text.contains("result_panel.mouse_filter = Control.MOUSE_FILTER_STOP"), "Result panel should keep button clicks")
