extends RefCounted

const MAIN_MENU_PATH := "res://scripts/main_menu.gd"

func run(t) -> void:
	var source := FileAccess.get_file_as_string(MAIN_MENU_PATH)
	var manager_source := FileAccess.get_file_as_string("res://scripts/match_manager.gd")
	var player_source := FileAccess.get_file_as_string("res://scripts/player_controller.gd")
	var hud_source := FileAccess.get_file_as_string("res://scripts/hud.gd")
	var settings_source := FileAccess.get_file_as_string("res://scripts/settings.gd")

	t.is_true(source.contains("func _start_playable_tutorial()"), "Main menu should start a playable tutorial")
	t.is_true(source.contains("if not PlayerData.tutorial_completed"), "First launch should check tutorial completion")
	t.is_true(source.contains("call_deferred(\"_start_playable_tutorial\")"), "Unfinished tutorial should enter playable training")
	t.is_true(source.contains("GameSettings.tutorial_mode = true"), "Playable tutorial should enable tutorial mode")
	t.is_true(source.contains("get_tree().change_scene_to_file(\"res://scenes/game.tscn\")"), "Playable tutorial should enter the game scene")
	t.is_true(source.contains("跳过"), "Legacy tutorial overlay should not show mojibake on its skip button")
	t.is_true(source.contains("PlayerData.mark_tutorial_completed(true)"), "Tutorial completion should be saved")
	t.is_true(source.contains("func _build_side_actions(star_label: Label)"), "Mobile home should tuck daily actions into the side")
	t.is_true(source.contains("SideDailyActions"), "Home should have a side daily action container")
	t.is_true(source.contains("func _make_edge_button(text: String)"), "Home should provide side button styling")
	t.is_true(source.contains("func _show_daily_hub(star_label: Label)"), "Daily entry should open a daily hub")
	t.is_true(source.contains("DailyHubOverlay"), "Daily rewards and tasks should be shown in an overlay")
	t.is_true(source.contains("func _show_achievement_list()"), "Home should provide a standalone achievement list")
	t.is_true(source.contains("AchievementListOverlay"), "Achievement list should open in its own overlay")
	t.is_true(source.contains("PlayerData.get_achievements()"), "Achievement list should read saved achievement state")
	t.is_true(source.contains("成就列表"), "Achievement list should have a visible title")
	t.is_false(source.contains("root.add_child(daily_button)"), "Daily reward should not occupy the main first screen")
	t.is_false(source.contains("root.add_child(_build_daily_tasks_panel(star_label))"), "Daily task panel should not be directly on the first screen")
	t.is_true(source.contains("func _is_mobile_layout()"), "Home layout should adapt to mobile screens")
	t.is_true(source.contains("get_viewport_rect().size"), "Mobile detection should use viewport size")
	t.is_true(source.contains("var viewport_size := get_viewport_rect().size"), "Mobile detection variable should not shadow Control.size")
	t.is_false(source.contains("var size := get_viewport_rect().size"), "Home should not shadow Control.size")
	t.is_true(source.contains("panel.custom_minimum_size = Vector2(320 if _is_mobile_layout() else 560, 0)"), "Daily overlay should be compact on mobile")
	t.is_true(source.contains("button.add_theme_font_size_override(\"font_size\", 25)"), "Main menu primary buttons should use larger readable text")
	t.is_true(source.contains("button.add_theme_font_size_override(\"font_size\", 19)"), "Main menu small buttons should be larger than the old compact text")
	t.is_true(source.contains("_tutorial_body_label.add_theme_font_size_override(\"font_size\", 24)"), "Tutorial body text should be readable on phones")
	t.is_true(source.contains("button.size_flags_horizontal = Control.SIZE_SHRINK_CENTER"), "Menu buttons should not stretch across the whole phone screen")

	t.is_true(settings_source.contains("var tutorial_mode := false"), "Settings should carry transient tutorial mode")
	t.is_true(manager_source.contains("const TUTORIAL_ACTION_STEPS"), "Match manager should define playable tutorial steps")
	t.is_true(manager_source.contains("player.tutorial_action.connect(_on_tutorial_action)"), "Playable tutorial should listen to player actions")
	t.is_true(manager_source.contains("教学 1/6：拖动左摇杆移动"), "Playable tutorial should start with movement")
	t.is_true(manager_source.contains("教学完成：准备进入正式作战"), "Playable tutorial should show completion feedback")
	t.is_true(player_source.contains("signal tutorial_action(action: String)"), "Player should emit tutorial actions")
	t.is_true(player_source.contains("tutorial_action.emit(\"move\")"), "Player movement should advance tutorial")
	t.is_true(player_source.contains("tutorial_action.emit(\"grenade\")"), "Grenade input should advance tutorial")
	t.is_true(hud_source.contains("func show_tutorial_objective(text: String)"), "HUD should display playable tutorial objectives")
