extends RefCounted

func run(t) -> void:
	var source := FileAccess.get_file_as_string("res://scripts/ai_controller.gd")
	t.is_true(source.length() > 0, "AIController 源码必须可读取")
	t.is_true(source.contains("const DEFAULT_ATTACK_RANGE := 32.0"), "AI 默认攻击距离应为 32")
	t.is_true(source.contains("\"m416\": 45.0"), "M416 AI 攻击距离应为 45")
	t.is_true(source.contains("\"barrett\": 85.0"), "巴雷特 AI 攻击距离应为 85")
	t.is_true(source.contains("\"rpg\": 50.0"), "RPG AI 攻击距离应为 50")
	t.is_true(source.contains("_get_current_attack_range()"), "AI 行为应使用当前武器攻击距离")
	t.is_true(source.contains("PREFERRED_ATTACK_DISTANCE_BY_WEAPON"), "AI 应区分最大射程和有效交战距离，避免看到人就原地停步")
	t.is_true(source.contains("_get_current_preferred_attack_distance()"), "AI 行为应使用当前武器有效交战距离")
	t.is_true(source.contains("_preferred_distance_multiplier = 0.68"), "简单 AI 应更主动贴近到有效距离，弥补低命中率")
	t.is_true(source.contains("not has_firing_lane and dist > KEEP_DISTANCE"), "AI 视线被遮挡时应继续前压而不是原地停住")
	t.is_true(source.contains("var battle_route: Array[Vector3] = []"), "AI 应持有开局作战路线，避免无目的乱跑")
	t.is_true(source.contains("func set_battle_plan(route: Array[Vector3])"), "AI 应支持由比赛管理器注入作战方案")
	t.is_true(source.contains("_advance_route_waypoint()"), "AI 路线巡逻应按航点推进")
	t.is_true(source.contains("_update_stuck_recovery(delta)"), "AI 应检测卡住并切换航点，避免原地转圈")
	t.is_true(source.contains("_can_engage_candidate(candidate)"), "AI 不应全图透视追人，应基于近距离/视线接敌")
	t.is_true(source.contains("_wander_angle = 0.0"), "AI 执行作战路线时不应随机偏航乱跑")
	t.is_true(source.contains("state = AIState.PATROL") and source.contains("_advance_route_waypoint()"), "AI 卡住时应回到作战路线并推进航点")
	t.is_true(source.contains("func _get_obstacle_steered_direction(desired_dir: Vector3) -> Vector3"), "AI 移动应先做局部避障，不应直线撞墙")
	t.is_true(source.contains("func _is_direction_blocked(dir: Vector3, distance: float) -> bool"), "AI 应用前方射线检测墙体")
	t.is_true(source.contains("_stuck_escape_timer = STUCK_ESCAPE_SECONDS"), "AI 卡墙时应进入短时脱困方向，而不是原地转圈")
	t.is_true(source.contains("_choose_escape_direction()"), "AI 卡住时应选择左右更通畅的脱困方向")
	t.is_true(source.contains("state == AIState.ATTACK or state == AIState.CHASE"), "AI 只应在战斗/追击中随机跳跃，巡逻路线不应乱跳")

	var match_source := FileAccess.get_file_as_string("res://scripts/match_manager.gd")
	t.is_true(match_source.contains("func get_battle_plan_route(team: String, bot_index: int, spawn_pos: Vector3) -> Array[Vector3]"), "比赛开始前应基于地图生成 AI 作战路线")
	t.is_true(match_source.contains("bot.set_battle_plan(get_battle_plan_route"), "生成 AI 后应立即注入作战路线")
	var pickup_source := FileAccess.get_file_as_string("res://scripts/ammo_pickup.gd")
	t.is_true(source.contains("SEEK_AMMO"), "AI 应包含寻找弹药箱状态")
	t.is_true(source.contains("_needs_ammo()"), "AI 应在没子弹时检测补给需求")
	t.is_true(source.contains("get_closest_ammo_drop(self)"), "AI 没子弹时应请求最近弹药箱")
	t.is_true(source.contains("AIState.SEEK_AMMO"), "AI 行为应切换到寻找弹药箱状态")
	t.is_true(source.contains("collect_ammo_drop(ammo_target, self)"), "AI 靠近弹药箱时应主动触发拾取")
	t.is_true(match_source.contains("func get_closest_ammo_drop(requester: Node3D) -> AmmoPickup"), "比赛管理器应提供最近弹药箱查询")
	t.is_true(match_source.contains("func collect_ammo_drop(drop: AmmoPickup, pickup_unit: Node3D)"), "比赛管理器应允许玩家和 AI 共用拾取逻辑")
	t.is_true(match_source.contains("_get_weapon_system(pickup_unit)"), "弹药箱拾取应通过单位武器系统补给")
	t.is_true(pickup_source.contains("collector: Node3D"), "弹药箱拾取信号应允许 AI 作为拾取者")
	t.is_true(pickup_source.contains("body is AIController"), "弹药箱应允许 AI 触发拾取")

	var player_source := FileAccess.get_file_as_string("res://scripts/player_controller.gd")
	t.is_true(source.contains("func set_spectate_hidden(hidden: bool)"), "AI 应提供观战隐藏视觉接口")
	t.is_true(source.contains("body_model.visible = not hidden"), "观战隐藏应隐藏 AI 本体")
	t.is_true(source.contains("weapon_mount.visible = not hidden"), "观战隐藏应隐藏 AI 手持武器")
	t.is_true(player_source.contains("_set_spectate_target(targets[0])"), "进入观战应通过统一方法设置目标")
	t.is_true(player_source.contains("_spectate_hidden_target.set_spectate_hidden(false)"), "切换观战目标时应恢复上一个目标视觉")
	t.is_true(player_source.contains("_spectate_target.set_spectate_hidden(true)"), "当前观战目标应隐藏视觉避免遮挡")
